resources:
  - name: every-30s
    type: time
    icon: clock-outline
    source:
      interval: 30s
  - name: apigee-gitops-repo
    type: git
    icon: github
    source:
      uri: https://github.com/anaik91/apigee-gitops.git
      branch: main
      paths:
      - src/*
      - pipeline/*.sh

  - name: apigee-runner-image
    type: docker-image
    icon: docker
    source:
      repository: ((docker-image-repo-name))/apigee-gitops-image
      tag: latest
      username: ((docker-registry-username))
      password: ((docker-registry-password))

# Reusable task configuration
task_run_apigee_script: &task_run_apigee_script_def
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: ((docker-image-repo-name))/apigee-gitops-image
      tag: latest
      username: ((docker-registry-username))
      password: ((docker-registry-password))
  inputs:
    - name: apigee-gitops-repo
  outputs: # Define an output for the status file
    - name: task-status
  params:
    GCP_SA_KEY_JSON: ((apigee-service-account-key))
    APIGEE_ORGANIZATION: ((apigee-org))
    APPLY_CHANGES: "false"
    CONFIG_PATH_IN_REPO: "src"
    GCP_PROJECT_ID_FOR_LOGGING: ((apigee-service-account-key))
  run:
    path: sh
    args:
      - -euc
      - |
        echo "Starting Apigee Sync..."
        ls -l
        bash apigee-gitops-repo/pipeline/deploy.sh
        echo "Done with Apigee Apigee Sync......"
jobs:
  # --- Organization-Scoped Resource Jobs ---
  - name: sync-developers # Renamed
    public: true
    plan:
      - get: apigee-gitops-repo
        trigger: true
      - get: every-30s
        trigger: true
      - get: apigee-runner-image
        trigger: false
      - task: run-sync-developers
        config:
          <<: *task_run_apigee_script_def
        params:
          RESOURCE_TYPE: "developers"
          APPLY_CHANGES: "false"
          # APIGEE_ENVIRONMENT not needed

  - name: sync-apiproducts # Renamed
    public: true
    plan:
      - get: apigee-gitops-repo
        trigger: true
      - get: every-30s
        trigger: true

      - get: apigee-runner-image
        
        trigger: false
      - task: run-sync-apiproducts
        config:
          <<: *task_run_apigee_script_def
        params:
          RESOURCE_TYPE: "apiproducts"
          APPLY_CHANGES: "false"

  # --- Environment-Scoped Resource Jobs ---
  - name: sync-targetservers # Renamed
    public: true
    plan:
      - get: apigee-gitops-repo
        trigger: true
      - get: every-30s
        trigger: true

      - get: apigee-runner-image
        
        trigger: false
      - task: run-sync-targetservers
        config:
          <<: *task_run_apigee_script_def
        params:
          RESOURCE_TYPE: "targetservers"
          APPLY_CHANGES: "false"
          APIGEE_ENVIRONMENT: ((apigee-env))

  - name: sync-resourcefiles # Renamed
    public: true
    plan:
      - get: apigee-gitops-repo
        trigger: true
      - get: every-30s
        trigger: true

      - get: apigee-runner-image
        
        trigger: false
      - task: run-sync-resourcefiles
        config:
          <<: *task_run_apigee_script_def
        params:
          RESOURCE_TYPE: "resourcefiles"
          APPLY_CHANGES: "false"
          APIGEE_ENVIRONMENT: ((apigee-env))

  - name: sync-flowhooks # Renamed
    public: true
    plan:
      - get: apigee-gitops-repo
        trigger: true
      - get: every-30s
        trigger: true

      - get: apigee-runner-image
        
        trigger: false
      - task: run-sync-flowhooks
        config:
          <<: *task_run_apigee_script_def
        params:
          RESOURCE_TYPE: "flowhooks"
          APPLY_CHANGES: "false"
          APIGEE_ENVIRONMENT: ((apigee-env))

  - name: sync-references # Renamed
    public: true
    plan:
      - get: apigee-gitops-repo
        trigger: true
      - get: every-30s
        trigger: true

      - get: apigee-runner-image
        
        trigger: false
      - task: run-sync-references
        config:
          <<: *task_run_apigee_script_def
        params:
          RESOURCE_TYPE: "references"
          APPLY_CHANGES: "false"
          APIGEE_ENVIRONMENT: ((apigee-env))

groups:
  - name: org-scoped
    jobs: [sync-developers, sync-apiproducts]
  - name: env-scoped
    jobs: [sync-targetservers, sync-resourcefiles, sync-flowhooks, sync-references]